variable "vpc_id" {}
variable "infra-basic-settings" {}
variable "private_subnet_ids" {}
variable "aws_ecr_repository_main_repository_url" {}
variable "aws_ecr_repository_web_repository_url" {}
variable "alb_tg_main_arn" {}
variable "aws_lb_listener_https_arn" {}
variable "aws_rds_endpoint" {}
variable "rds_user_name" {}
variable "rds_password" {}
variable "secret_key" {}
variable "ecr_app_push_complete" {}
variable "ecr_web_push_complete" {}